version: "3.9"
volumes:
  acmeroot:

  certdir:

  certbotdata:

  avsconfigdir:

services:
  avsrouter:
    image: "ghcr.io/fails-components/avsrouter:${FAILS_TAG:-master}"
    volumes:
      - acmeroot:/usr/src/avsrouter/challenges:ro
      - certdir:/usr/src/avsrouter/certs:ro
      - avsconfigdir:/usr/src/avsrouter/config:rw   
    restart: always
    ports:
      - "443:443"
      - "443:443/udp"
      - "80:80"
    healthcheck:
      test: curl --fail http://localhost/health || exit 1
      interval: 60s
      retries: 5
      start_period: 20s
      timeout: 10s
    
    environment:
# region config, needs to be set externally, aswell as AVSDOMAIN
      - AVSCONFIG
      - AVSROUTERURL=https://${AVSDOMAIN}/avfails
      - AVSROUTERWSURL=wss://${AVSDOMAIN}/avfails
      - AVSMAXCLIENTS=${AVSMAXCLIENTS:-20}
      - AVSMAXREALMS=${AVSMAXREALMS:-5}
      - AVSROUTERHOST=0.0.0.0
      - AVSROUTERPORT=443
# filename for key and cert fopr http1, checked all 5 sec for changes
      - AVSROUTERKEYPEM=/usr/src/avsrouter/certs/live/${AVSDOMAIN}/privkey.pem
      - AVSROUTERCERTPEM=/usr/src/avsrouter/certs/live/${AVSDOMAIN}/fullchain.pem
# dirname for serving acme challenges
      - AVSROUTERACMEHTTP1DIR=/usr/src/avsrouter/challenges
# time zones to find suitable restart times for certificate rotations defaults to Europe/Berlin      
      - AVSTIMEZONE
  certbot:
    image: certbot/certbot
    depends_on:
      avsrouter:
        condition: service_healthy
    restart: always
    volumes:
      - certbotdata:/var/lib/letsencrypt:rw
      - certdir:/etc/letsencrypt:rw
      - acmeroot:/var/www/html:rw
    entrypoint: /bin/sh -c 'trap exit TERM; 
      if [ ! -f /etc/letsencrypt/certs/live/${AVSDOMAIN}/privkey.pem ];
      then
        echo "Obtain initial certificate!";
        certbot certonly --webroot -w /var/www/html -d ${AVSDOMAIN}  --non-interactive --agree-tos
           --register-unsafely-without-email ${STAGING:---staging};
      fi;
      while :;
      do
        echo "Check certificate renewal"; 
        certbot renew;
        echo "Sleep for 12 h"; 
        sleep 12h & wait $${!};
      done;' 



