apiVersion: v1
kind: Service
metadata:
  name: {{ include "fails-components.fullname" . }}-apphandler
  labels:
    {{- include "fails-components.labels" . | nindent 4 }}-apphandler
spec:
  type: {{ .Values.apphandler.service.type }}
  ports:
    - port: {{ .Values.apphandler.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fails-components.selectorLabels" . | nindent 4 }}-apphandler
