apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fails-components.fullname" . }}-authhandler
  labels:
    {{- include "fails-components.labels" . | nindent 4 }}-authhandler
spec:
  {{- if not .Values.authhandler.autoscaling.enabled }}
  replicas: {{ .Values.authhandler.replicaCount }}
  {{- end }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "fails-components.selectorLabels" . | nindent 6 }}-authhandler
  template:
    metadata:
      annotations:
      {{- with .Values.podAnnotations }}
        rollme: {{ randAlphaNum 5 | quote }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fails-components.selectorLabels" . | nindent 8 }}-authhandler
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
#      serviceAccountName: {{ include "fails-components.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-authhandler
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryprefix }}authhandler:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FAILS_KEYS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keys.secretName }}
                  key: {{ .Values.keys.secretKey }}
                  optional: false
            - name: FAILS_STATIC_SECRET
              value: "dummy"
            - name: REDIS_HOST
              value: "{{ .Values.redis.host }}"
            - name: REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.secretName }}
                  key: {{ .Values.redis.secretKey }}
                  optional: false              
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.authhandler.resources | nindent 12 }}
      {{- with .Values.authhandler.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authhandler.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.authhandler.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
