apiVersion: v1
kind: Service
metadata:
  name: {{ include "fails-components.fullname" . }}-authhandler
  labels:
    {{- include "fails-components.labels" . | nindent 4 }}-authhandler
  {{- with .Values.serviceAnnotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.authhandler.service.type }}
  ports:
    - port: {{ .Values.authhandler.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if  .Values.useClusterIPforService }}
      nodePort: {{ .Values.serviceNodePort }}
      {{- end }}
  selector:
    {{- include "fails-components.selectorLabels" . | nindent 4 }}-authhandler
  {{- if  .Values.useClusterIPforService }}
  externalTrafficPolicy: Local
  {{- end }}
  
