apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fails-components.fullname" . }}-housekeeping
  labels:
    {{- include "fails-components.labels" . | nindent 4 }}-housekeeping
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "fails-components.selectorLabels" . | nindent 6 }}-housekeeping
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fails-components.selectorLabels" . | nindent 8 }}-housekeeping
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
#      serviceAccountName: {{ include "fails-components.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-housekeeping
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryprefix }}housekeeping:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FAILS_KEYS_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.keys.secretName }}
                  key: {{ .Values.keys.secretKey }}
                  optional: false
            - name: FAILS_STATIC_WEBSERV_TYPE
              value: "openstackswift"
            - name: FAILS_STATIC_SAVE_TYPE
              value: "openstackswift"
            - name: FAILS_STATIC_SECRET
              value: "dummy"
            - name:  REDIS_HOST
              value: "{{ .Values.redis.host }}"
            - name:  REDIS_PORT
              value: "{{ .Values.redis.port }}"
            - name: REDIS_PASS
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.redis.secretName }}
                  key: {{ .Values.redis.secretKey }}
                  optional: false
            - name: FAILS_MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.mongo.secretName }}
                  key: {{ .Values.mongo.secretKeyPassword }}
                  optional: false               
            - name: FAILS_MONGO_URL
              value: "mongodb://{{ .Values.mongo.user }}:$(FAILS_MONGO_PASSWORD)@{{ .Values.mongo.mongoConnection }}"
            # needed if swift is used
            - name: FAILS_SWIFT_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.swift.secretName }}
                  key: {{ .Values.swift.secretKeySwiftKey }}
                  optional: false
            - name: FAILS_SWIFT_ACCOUNT
              value: "{{ .Values.swift.account }}"
            - name: FAILS_SWIFT_CONTAINER
              value: "{{ .Values.swift.container }}"
            - name: FAILS_SWIFT_BASEURL
              value: "{{ .Values.swift.baseurl }}" 
            - name: FAILS_SWIFT_AUTH_BASEURL
              value: "{{ .Values.swift.authbaseurl }}" 
            - name: FAILS_SWIFT_USERNAME
              value: "{{ .Values.swift.username }}" 
            - name: FAILS_SWIFT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.swift.secretName }}
                  key: {{ .Values.swift.secretKeySwiftPassword }}
                  optional: false
            - name: FAILS_SWIFT_DOMAIN
              value: "{{ .Values.swift.domain }}" 
            - name: FAILS_SWIFT_PROJECT
              value: "{{ .Values.swift.project }}"
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy.txt
            initialDelaySeconds: 60
            periodSeconds: 30
          resources:
            {{- toYaml .Values.housekeeping.resources | nindent 12 }}
      {{- with .Values.housekeeping.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.housekeeping.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.housekeeping.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
