apiVersion: v1
kind: Service
metadata:
  name: {{ include "fails-components.fullname" . }}-ltihandler
  labels:
    {{- include "fails-components.labels" . | nindent 4 }}-ltihandler
  {{- with .Values.ltihandler.service.annotations }}
  annotations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
spec:
  type: {{ .Values.ltihandler.service.type }}
  ports:
    - port: {{ .Values.ltihandler.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "fails-components.selectorLabels" . | nindent 4 }}-ltihandler
