apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fails-components.fullname" . }}-staticserver
  labels:
    {{- include "fails-components.labels" . | nindent 4 }}-staticserver
spec:
  {{- if not .Values.staticserver.autoscaling.enabled }}
  replicas: {{ .Values.staticserver.replicaCount }}
  {{- end }}
  strategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate
  selector:
    matchLabels:
      {{- include "fails-components.selectorLabels" . | nindent 6 }}-staticserver
  template:
    metadata:
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "fails-components.selectorLabels" . | nindent 8 }}-staticserver
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
#      serviceAccountName: {{ include "fails-components.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}-staticserver
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repositoryprefix }}staticserver-noassets:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }} 
          env:
            - name: FAILS_APP_CONFIG_JSON
              value: |
              {{ .Values.app.config | indent 2}}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /static/app/
              port: http
          readinessProbe:
            httpGet:
              path: /static/app/
              port: http
          resources:
            {{- toYaml .Values.staticserver.resources | nindent 12 }}
      {{- with .Values.staticserver.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.staticserver.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.staticserver.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
